# Generated by Django 3.0.8 on 2020-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200930_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
