# Generated by Django 3.1.1 on 2020-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201001_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
