# Generated by Django 3.1.1 on 2020-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('forex', 'forex'), ('crypto', 'crypto'), ('chiêm tinh', 'chiêm tinh')], max_length=255, null=True),
        ),
    ]
