# Generated by Django 3.0.8 on 2020-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
